### ISSUE TITLE
Removed from Runelite?

### ISSUE THREAD

**Issue by SlayTheMonkey** [skiclimbcode/herblore-recipes#16]
Hey there!

I'm a big fan of the plugin and noticed it has vanished from Runelite - if this is due to some kind of patch causing incompatibility I'd be happy to help pin things together if you'd like a hand, I know just enough to be dangerous!

I'd be surprised if it got pulled by Jagex but I don't want to manually re-add the plugin if this is the case - just wanted to see what's up :D

**Comment by skiclimbcode** [comment]
I believe it should be resolved now
