### ISSUE TITLE
Plugin not working since inventory rework.

### ISSUE THREAD

**Issue by Topsu7** [skiclimbcode/herblore-recipes#18]
Since the update on inventory systems on April 20 the plugin hasn't worked. Similar plugins like "Green Thumb" were updated pretty quickly, so I guess it shouldn't be a major update? Thanks for the plugin anyway, it is awesome!

**Comment by sybren9** [comment]
@skiclimbcode Green thumb's [fix](https://github.com/Asthereon/green-thumb/commit/7e6b07c0aeff5849d8c0019a5c19251eb8557d1b)

**Comment by skiclimbcode** [comment]
I've got a PR open for this now: https://github.com/runelite/plugin-hub/pull/2605

Let me know if there are any lingering issues while using the plugin!

**Comment by skiclimbcode** [comment]
https://github.com/runelite/plugin-hub/pull/2606

Pull request is open! When it gets merged, please let me know if you find any other bugs :). Sorry it took so long to get to this, busy schedule atm.
