### ISSUE TITLE
Feature Request: Overlay info when hovering over a placeholder for an herb.

### ISSUE THREAD

**Issue by harryt04** [skiclimbcode/herblore-recipes#22]
Currently, if you hover your mouse over a bank placeholder for an herb (there is quantity 0 of that herb in your bank), the overlay shows the weight of the herb, but not the info from this plugin. Is it possible to also show the plugin info in this case? Or add an option to opt into this behavior if you wouldn't want it by default?
![Screenshot (2)](https://user-images.githubusercontent.com/22422276/166160832-6d14c50a-9484-480c-8ad5-a086fda78c25.png)

**Comment by skiclimbcode** [comment]
PR is open! https://github.com/runelite/plugin-hub/pull/2668
