### ISSUE TITLE
Red Spider's Eggs not showing tooltips

### ISSUE THREAD

**Issue by MattZeeX** [skiclimbcode/herblore-recipes#7]
Hi, I think this is a really cool plugin. I just got it and decided to try mousing over the limited supply of herblore supplies I have in my bank and I went to red spider's eggs since I've recently been doing super restores and have them stocked up. 
![image](https://user-images.githubusercontent.com/49168219/120814642-308fbe80-c5a3-11eb-90f2-ec6b02394011.png)
I noticed I didn't get a tooltip so I went to the options to double check I had the tooltips enabled for secondaries.
![image](https://user-images.githubusercontent.com/49168219/120814677-37b6cc80-c5a3-11eb-8e3b-9273481ad021.png)
(I did)

So I then went to mouse over my eyes of newt which I have for some reason and noticed it was working.
![image](https://user-images.githubusercontent.com/49168219/120814547-1950d100-c5a3-11eb-9b59-45b883c20db2.png)
I double checked the wiki to make sure red spider's eggs were used for herblore.
![image](https://user-images.githubusercontent.com/49168219/120815273-c1669a00-c5a3-11eb-853d-9e1401a37250.png)
(and of course they are cause I made super restores before, but I double checked)

The eggs are used as a secondary for a lot of potions so I thought maybe the tooltip wasn't created because it would be too big? Might be a stupid thought though.

I literally only just got this plugin cause I thought it was cool and haven't had any time to mess about with it yet, but I noticed the issue with the spider eggs so I thought I'd point it out. I haven't done any actual troubleshooting like restarting my game or disabling other plugins to isolate the issue, so sorry if this is useless, just wondering if you can reproduce the issue on your end.

Thanks for the cool plugin.

**Comment by skiclimbcode** [comment]
Hey thanks for raising this issue! Been busy few days but I'll take a look today after work!
