### ISSUE TITLE
Herblore Recipe recommendation (Top Tier I promise.)

### ISSUE THREAD

**Issue by Bolarino** [skiclimbcode/herblore-recipes#9]
Hey there!

I LOVE your herblore plugin, But! I think it would be incredibly helpful if you added an option to only show the overlay in the bank interface. 
For Example: I have been getting a lot of uncleaned herbs from miscellania on my iron man.

i have to clean these herbs in my inventory, and it can take a while doing 400+ herbs at a time. I do LOVE the interface/overlay you've made but when I'm just trying to clean herbs, the interface definitely gets in in the way. It can be hard to see other items in my inventory when this info is displayed. I would much rather only be able to see the potion combination recipes while in the bank, When I'm trying to identify herbs, the infobox gets completely in the way and I can't see which herbs I'm identifying. 

Perhaps if you could add an option where the ingredient info ONLY shows while hovering in the BANK. That would be incredible. Thanks!!! - jwpjoe@gmail.com

**Comment by skiclimbcode** [comment]
Happy to see you're enjoying the plugin!

I like this recommendation! Thanks for the suggestion, I'll definitely get around to this when time permits :).

**Comment by skiclimbcode** [comment]
https://github.com/runelite/plugin-hub/pull/1691/ PR open

**Comment by skiclimbcode** [comment]
PR was merged!
